---
- name: install ca-certificates package and network tools (debian)
  when: ansible_os_family == 'Debian'
  apt:
    name:
     - apt-transport-https
     - ca-certificates
     - software-properties-common
     - curl
     - ntp
     - rsync
    state: present
    update_cache: yes
- name: install ca-certificates package and network tools (suse)
  when: ansible_os_family == 'Suse'
  zypper:
    name:
     - ca-certificates
     - curl
     - ntp
     - rsync
    state: present
    update_cache: yes
- name: disable requiretty
  lineinfile:
    dest: /etc/sudoers
    regexp: 'Defaults.*requiretty'
    state: absent
- name: ensure ntp is started (Debian)
  when: ansible_os_family == 'Debian'
  service:
    name: ntp
    state: started
    enabled: yes
- name: ensure ntp is started (Suse)
  when: ansible_os_family == 'Suse'
  service:
    name: ntpd
    state: started
    enabled: yes
- name: fix screen profile
  lineinfile:
    dest: /etc/screenrc
    line: 'shell -/bin/bash'
